org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

mod_name=FTB Echoes
mod_id=ftbechoes
mod_version=1

minecraft_version=26.1.2
supported_minecraft_versions=26.1.2
minecraft_version_range=[26.1.2,27)
# https://minecraft.fandom.com/wiki/Pack_format
pack_format=15

neoforge_version=26.1.2.93
neoforge_version_range=[26.1.2.1,27)
neoforge_loader_version_range=[4,)

#Mod Stuff
archives_base_name=ftb-echoes
maven_group=dev.ftb.mods

#CurseForge
curseforge_id=1369870

#Deps
ftb_library_version=26.1.2.7-SNAPSHOT
ftb_teams_version=26.1.2.4
ftb_xmod_compat_version=26.1.2.3-SNAPSHOT
ftb_quests_version=26.1.2.3-SNAPSHOT
curios_version=15.0.0+26.1.2
magic_coins_version=7937725
sg_economy_version=8041335
jei_version=29.20.0.60
jade_curse_id=8326300
